#!/usr/bin/env bash

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
    exit
fi

if [ "$env" != "local" ]; then
    echo "Caching configuration..."
    (cd /var/www/html && php artisan config:cache && php artisan route:cache && php artisan view:cache)
fi

if [ "$role" = "app" ]; then
    echo "Starting the server..."
    exec /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80

elif [ "$role" = "queue" ]; then
    echo "Starting the queue..."
    php /var/www/html/artisan horizon

elif [ "$role" = "scheduler" ]; then
    echo "Starting the scheduler..."
    php /var/www/html/artisan schedule:work --verbose --no-interaction

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
