#!/usr/bin/env bash

ENV=${APP_ENV:-production}
HOST=0.0.0.0
PORT=80

if [ "$ENV" = "production" ]; then
  php -d variables_order=EGPCS artisan octane:start --host=$HOST --port=$PORT --server=swoole
else
  # Start in watch mode
  php -d variables_order=EGPCS artisan octane:start --watch --host=$HOST --port=$PORT --server=swoole
fi
