name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          set -e
          export PATH=$PATH:/root/.config/herd-lite/bin
          cd laravel-dockerfile
          git pull origin main
          make ENV=production PORT=8080 build
          php artisan migrate --force
          make ENV=production PORT=8080 start
