name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          set -e
          export PATH=$PATH:/root/.config/herd-lite/bin
          cd laravel-dockerfile
          git pull origin main

          composer install --optimize-autoloader --no-progress --no-interaction
          pnpm install --force
          pnpm run build

          docker compose up -d --build app
          docker image prune -f || true
